node {
    docker.image('node:16-buster-slim').inside('-p 3000:3000 -u root') {
        stage('Build') {
            sh 'npm install'
        }
        stage('Test') {
            sh './jenkins/scripts/test.sh'
        }
        stage('Manual Approval Stage'){
            input message: 'Lanjutkan ke tahap Deploy? (Click "Proceed" to continue)'            
        }
        stage('Deploy') {
            sh 'apt-get update && apt-get install -y openssh-client'
            sh './jenkins/scripts/deliver.sh'
            sshagent(credentials: ['EC2-SSH-KEY']){
            sh 'scp -o StrictHostKeyChecking=no -r build ubuntu@13.211.175.69:/home/ubuntu/JCalvin/react'
            }
            sleep(time: 60, unit: 'SECONDS')
            sh './jenkins/scripts/kill.sh'
        }
    }    
}
